### ISSUE TITLE
nvme_rw is failing to write/read on the SSD

### ISSUE THREAD

**Issue by Amit0039** [xnox/nvme-user#1]
It is failing with the below mentioned error -

root@amit # ./firmware/nvme_rw /dev/nvme0n1
/dev/nvme0n1: Invalid argument
root@amit #

It was traced out that the metadata should not be zero.
The below mentioned condition is supposed to be false in the driver code.

 ((io.metadata & 3) || !io.metadata)

When it was changed to 4.
Ex:-
io.metadata = (unsigned long)4;
in nvme_rw.c file.

The following error was seen.

controller:root:amit # ./firmware/nvme_rw /dev/nvme0n1
/dev/nvme0n1: Bad address
controller:root:amit #

Why did it happen ?

**Comment by xnox** [comment]
maybe go to upstream that developed this tool.... google it, should be easy to find.

i only forked it to add a patch to see namespace id, and to verify that i don't have one setup on my device.
